source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform:ios, '9.0'

abstract_target '_' do

    #    pod 'DTCoreText', '~> 1.6.21'
    pod 'ReactiveObjC'
    pod 'IAPHelper'       #https://github.com/saturngod/IAPHelper
    pod 'YYModel'         #https://github.com/ibireme/YYModel
    pod 'YYCategories'
    pod 'YYCache'
    pod 'MBProgressHUD'     #http://www.bukovinski.com
    pod 'DZNEmptyDataSet'   #https://github.com/dzenbot/DZNEmptyDataSet
    pod 'FMDB/standalone'              #https://github.com/ccgus/fmdb
    pod 'MJRefresh'                     #https://github.com/CoderMJLee/MJRefresh
    pod 'hpple', :git => 'https://github.com/topfunky/hpple.git'             #https://github.com/topfunky/hpple
    pod 'DGActivityIndicatorView'  #https://github.com/gontovnik/DGActivityIndicatorView
    pod 'PinYin4Objc'              #https://github.com/kimziv/PinYin4Obj
    pod 'JZNavigationExtension', '1.5.0.1' #https://github.com/JazysYu/JZNavigationExtension
    pod 'AMPopTip'          #https://github.com/andreamazz/AMPopTip
    pod 'SAMKeychain'
    pod 'DZNWebViewController'          #https://github.com/dzenbot/DZNWebViewController
    pod 'DACircularProgress'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'IQKeyboardManager'
    pod 'SDWebImage/GIF'
    pod 'SDWebImage/WebP'
    pod 'AFNetworking'
    pod 'SSZipArchive'
    pod 'AVOSCloud'

    #解决依赖SDWebImage版本问题
    pod 'IDMPhotoBrowser', :git => 'https://github.com/developforapple/IDMPhotoBrowser.git'
    pod 'JBChartView' , :git => 'https://github.com/developforapple/JBChartView.git'
    pod 'ChameleonFramework'
    pod 'MXParallaxHeader'
    pod 'FCUUID'
    
    target 'SPDev' do
        pod 'Google-Mobile-Ads-SDK'
    end
    
    target 'SPAd' do
        pod 'Google-Mobile-Ads-SDK'
    end
    
    target 'SPOld' do
        pod 'Google-Mobile-Ads-SDK'
    end
    
    target 'SPPro' do
    
    end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = 'Swift 4.0'
            config.build_settings['VALID_ARCHS'] = 'armv7 arm64'
            
            # 解决 AVOSCloud 中无法使用sqlite3.framework的问题
            if config.build_settings['PRODUCT_NAME'] == 'AVOSCloud'
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = "$(inherited) $PODS_CONFIGURATION_BUILD_DIR/sqlite3"
                config.build_settings['OTHER_CFLAGS'] = "$(inherited) -DFMDB_SQLITE_STANDALONE"
            end
        end
    end
end
