source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform:ios, '8.0'
target 'DOTA2ShiPing'

pod 'ReactiveObjC'
pod 'IAPHelper'       #https://github.com/saturngod/IAPHelper
pod 'YYModel', '~> 1.0.4'           #https://github.com/ibireme/YYModel
pod 'YYCategories'
pod 'YYCache'

pod 'MBProgressHUD'     #http://www.bukovinski.com
pod 'DZNEmptyDataSet', '~> 1.8.1'   #https://github.com/dzenbot/DZNEmptyDataSet
pod 'FMDB', '~> 2.7.2'   #https://github.com/ccgus/fmdb
pod 'MJRefresh'                     #https://github.com/CoderMJLee/MJRefresh
pod 'hpple', '~> 0.2.0'             #https://github.com/topfunky/hpple
pod 'DGActivityIndicatorView', '~> 2.0' #https://github.com/gontovnik/DGActivityIndicatorView
pod 'PinYin4Objc', '~> 1.1.1'       #https://github.com/kimziv/PinYin4Obj
pod 'JZNavigationExtension', '~> 1.5.0.1' #https://github.com/JazysYu/JZNavigationExtension
pod 'AMPopTip', '~> 1.1.1'          #https://github.com/andreamazz/AMPopTip

pod 'SAMKeychain'
pod 'DZNWebViewController'          #https://github.com/dzenbot/DZNWebViewController

pod 'DACircularProgress'
pod 'pop'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'IQKeyboardManager'

pod 'SDWebImage/GIF'
pod 'SDWebImage/WebP'

pod 'AFNetworking', '~> 3.1.0'      #https://github.com/AFNetworking/AFNetworking

pod 'SSZipArchive'
pod 'AVOSCloud'

#解决依赖SDWebImage版本问题
pod 'IDMPhotoBrowser', :git => 'https://github.com/developforapple/IDMPhotoBrowser.git'
pod 'JBChartView' , :git => 'https://github.com/developforapple/JBChartView.git'
#pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git'

pod 'ChameleonFramework', '~> 2.1.0'

pod 'MXParallaxHeader'

pod 'Google-Mobile-Ads-SDK'
